Integration tests
MartaSzuran/birdwatcher pull request #1
Opened 2022-07-26 08:27 UTC by MartaSzuran

I have problem witch checking save button - disable action <- on app works, on test don't, so I suppose some things maybe with timing ... 

Instead I thing I have check everything, just please review guys :D

2022-07-26 11:59 UTC, DawidDamek reviewed
Żeby przetestować czy działa save możesz wypełnić dane i sprawdzić czy wyświetli się modal po zapisaniu. Przekierowania z tego modala trzeba będzie sprawdzic w acceptance tests

2022-07-26 11:59 UTC, DawidDamek commented on tests/integration/components/observation-form/component-test.js
> +  });
💪

2022-07-26 11:59 UTC, DawidDamek commented on tests/integration/components/observation-form/component-test.js
> +    assert.dom('[data-test-input-notes]').hasValue('');
tak możesz sprawdzić czy nie ma value, powinno zadziałać

```suggestion
    assert.dom('[data-test-input-pikaday]').hasNoValue()
    assert.dom('[data-test-input-birdname]').hasNoValue()
    assert.dom('[data-test-input-location]').hasNoValue()
    assert.dom('[data-test-input-notes]').hasNoValue()
```

2022-07-30 08:52 UTC, wozny1989 requested changes

2022-07-30 08:52 UTC, wozny1989 commented on tests/integration/components/observation-form/component-test.js
> +    assert.dom('[data-test-input-notes]').hasNoValue('');
`hasNoValue` takes only message attribute https://github.com/simplabs/qunit-dom/blob/master/API.md
```suggestion
    assert.dom('[data-test-input-pikaday]').hasNoValue();
    assert.dom('[data-test-input-birdname]').hasNoValue();
    assert.dom('[data-test-input-location]').hasNoValue();
    assert.dom('[data-test-input-notes]').hasNoValue();
```

2022-07-30 08:52 UTC, wozny1989 commented on tests/integration/components/observation-form/component-test.js
> +    );
how about destructure `observation` for each cases:
```suggestion
   const { observationDate, birdname, notes } = this.observation;
    const stringDate = moment(observationDate).format(
      'YYYY-MM-DD'
    );
```

2022-07-30 09:31 UTC, MartaSzuran commented on tests/integration/components/observation-form/component-test.js
> +    assert.dom('[data-test-input-notes]').hasNoValue('');
Done !! :)

2022-07-30 09:31 UTC, wozny1989 approved these changes
LGTM!

2022-07-30 09:31 UTC, merged