Creating_settings_route
MartaSzuran/birdwatcher pull request #5
Opened 2022-08-03 11:53 UTC by MartaSzuran

2022-08-03 12:10 UTC, wozny1989 requested changes
🚀

2022-08-03 12:10 UTC, wozny1989 commented on app/home/user-settings/controller.js
> +  @tracked photo = this.model.photoURL;
Declare empty `@tracked` and set in `constructor`

2022-08-03 12:10 UTC, wozny1989 commented on app/home/user-settings/controller.js
> +  }
These actions are almost identical. Consider migrate to one, common action `onPropetyChange` or similar which take model key and override it value

2022-08-04 09:08 UTC, MartaSzuran commented on app/home/user-settings/controller.js
> +  @tracked photo = this.model.photoURL;
It has turned out that I don't need that declaration.

2022-08-04 09:23 UTC, wozny1989 approved these changes

2022-08-04 09:23 UTC, wozny1989 commented on app/home/user-settings/controller.js
> +  }
🚀

2022-08-04 09:23 UTC, merged