User page acceptance tests
MartaSzuran/birdwatcher pull request #9
Opened 2022-08-17 12:03 UTC by MartaSzuran

Please review if I am on track :) 

[x] home/user

2022-08-17 13:12 UTC, wozny1989 requested changes
Github told you everything (why tests are failing) 😄
![image](https://user-images.githubusercontent.com/36460224/185142315-01737a69-afbb-4d37-a40f-1d7de4a00aa5.png)

The rest looks good 👌 

About ugly formatting text in Description this Pull Request I am referring to my last comment previous PR => https://github.com/MartaSzuran/birdwatcher/pull/8#issuecomment-1211675091

2022-08-25 13:38 UTC, DawidDamek requested changes
great, but there are some things tu cut 😀

2022-08-25 13:38 UTC, DawidDamek commented on app/home/edit-observation/controller.js
> +    this.model[propName] = value;
❤️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +      .hasAttribute('src', '/assets/images/bird.png');
If You check anything else than `.exists()` you can skip it because other methods will also check if element exists. For instance if you check only `.hasAttribute()` and this element doesn't exist this test will tell you that. So use `.exists()` only when You don't check anything else

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +    assert.dom('[data-test-navbar-profile]').hasText('Profile');
same☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +    assert.dom('[data-test-navbar-observations]').hasText('Observations');
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +    assert.dom('[data-test-navbar-add-observation]').hasText('Add observation');
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +    assert.dom('[data-test-navbar-home]').hasText('Home');
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home-test.js
> +    assert.dom('[data-test-navbar-logout]').hasText('Logout');
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/edit-observation/edit-observation-test.js
> +      );
same as before but quick reminder, that You can link methods. 
```suggestion
    assert.dom('[data-test-input-edit-obser-pikaday]').exists().hasValue(
        moment(this.currentObservation.observationDate).format('YYYY-MM-DD')
      );
```

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/edit-observation/edit-observation-test.js
> +      .hasValue(this.currentObservation.birdname);
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/edit-observation/edit-observation-test.js
> +    document.elementFromPoint(x + width / 2, y + height / 2).click();
🚀

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/edit-observation/edit-observation-test.js
> +      .hasValue(this.currentObservation.notes);
☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/user/user-test.js
> +      owner: this.sessionService.currentUser,
In our cases we had to declare relations using id like: 
```js
owner.id=this.sessionService.currentUser.id
```
but I think it's ok if it works

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/user/user-test.js
> +    await visit('user');
I don't understand this part of test, why do you click settings button and then redirect manually by visit? If it is `LinkTo` it should change route by itself and also if you click something you don't need to check `exist()`

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/user/user-test.js
> +    assert.strictEqual(currentURL(), 'user');
same here☝️🤔

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/user-settings/user-settings-test.js
> +      .hasAttribute('placeholder', this.sessionService.currentUser.username);
same☝️

2022-08-25 13:38 UTC, DawidDamek commented on tests/acceptance/home/user-settings/user-settings-test.js
> +    assert.strictEqual(currentURL(), '/user');
🤔

2022-08-26 08:39 UTC, DawidDamek approved these changes
👌

2022-08-26 08:39 UTC, DawidDamek commented on tests/acceptance/home/edit-observation/edit-observation-test.js
>          moment(this.currentObservation.observationDate).format('YYYY-MM-DD')
My previous comment was just reminder that you can link functions and `exists()` is not necessary there but you cal leave it as it is

2022-08-26 08:42 UTC, merged